disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Samiul Islam"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/logo.png"
  description = "Sun | Portfolio"
  copyright = "© 2025 Samiul Islam Sun. All rights reserved."

[params.author]
  name = "Samiul Islam Sun"
  
  email = "samiulsun.islam@gmail.com"
  image = "img/author.jpg"
  imageQuality = 96
  headline = "Code. Create. Conquer"
  bio = "Aspiring software engineer who loves learning, building, and solving problems."



  links = [
    { github = "https://github.com/samiulsun" },
    { linkedin = "https://linkedin.com/in/samiulsun" },
    { x-twitter  = "https://twitter.com/Sun_Samiul" },
    { instagram = "https://instagram.com/sun_samiul" },
    { email = "mailto:samiulsun.islam@gmail.com" },
  ]
